### ISSUE TITLE
Publishing 2.4.0 Features

### ISSUE THREAD

**Issue by hg-pyun** [hg-pyun/axios-logger#56]
## Summary
I'm sorry I'm late. When all the functions below are developed, we will publish 2.4.0.
It will be distributed sometime in August. Thank you for waiting.
Thank you for feedback @ClintEsteMadera, @Fylipp, @mirfilip, @xenoterracide, and others.

## Features
- [ ] Add body trimming (#55)
- [x] Support more loggers (#53) (#62) 
- [x] Placing HTTP method first, then the URL (#60) (#63) 
- [x] Allow for no timestamp being appended (#64)
- [x] Explicitly set defaults in the code, as documented (#65)

**Comment by hg-pyun** [comment]
#55 to be next feature.
