### ISSUE TITLE
Release 2.5.0

### ISSUE THREAD

**Issue by hg-pyun** [hg-pyun/axios-logger#74]
## List
- [x] Enriched README with more information on how to specify the logger function to be used. (#66)
- [x] Add log config into error logger with a promise (#72) (#73)
- [x] Customizing logger function doesn't work, always uses global config logger (#75) (#76)
- [x] Remove lib folder (#77) (#78)
- [ ] Add body trimming (#55)
- [ ] Show query params for GET requests (#67)
- [x] logger is a required but not actually used (#71)
- [ ] Set test env

**Comment by hg-pyun** [comment]
Upldate later blow features.
- Add body trimming (#55)
- Show query params for GET requests (#67)
- Set test env
